name: Auto Sync Main to Prod Repo

on:
  push:
    branches:
      - main  # Runs only when pushing to `main`

jobs:
  sync_branches:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Dev Repository
      - name: Checkout Dev Repo
        uses: actions/checkout@v4

      # Step 2: Push Code to Production Repo using PAT Token
      - name: Sync with Production Repo
        run: |
          git config --global user.email "hiral.patel@differenzsystem.com"
          git config --global user.name "Hiral Patel"
          git remote add prod_repo https://x-access-token:${{ secrets.PRODUCTION_TOKEN }}@github.com/patel-hiral/production.git
          git push prod_repo main:main --force  # Push main to main
