name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to allow merging

      - name: Add Production Remote
        run: git remote add prod git@github.com:patel-hiral/production.git

      - name: Fetch Latest Changes
        run: git fetch prod main  # Get latest changes from production

      - name: Merge or Rebase with Production
        run: |
          git checkout main
          git merge --no-edit prod/main || git rebase prod/main

      - name: Push to Production
        run: git push prod main


