name: Auto Merge Dev. to Production Repository

on:
  push:
    branches:
      - main  # Runs only when pushing to `dev`

jobs:
  sync_branches:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Dev Repository
      - name: Checkout Dev Repo
        uses: actions/checkout@v4

      # Step 2: Push Code to Production Repo
      - name: Sync with Production Repository
        run: |
          git config --global user.email "hiral.patel@differenzsystem.com"
          git config --global user.name "Hiral Patel"
          git remote add prod_repo https://x-access-token:${{ secrets.PROD_REPO_TOKEN }}@github.com/patel-hiral/production.git
          git push prod_repo dev:main --force
