name: Auto Sync Main to Prod Repo

on:
  push:
    branches:
      - main  # Runs when pushing to `main`

jobs:
  sync_branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev Repo
        uses: actions/checkout@v3

      - name: Add Production Repository as Remote
        run: |
          git config --global user.email "hiral.patel@differenzsystem.com"
          git config --global user.name "Hiral Patel"
          git remote add prod_repo https://x-access-token:${{ secrets.PRODUCTION_TOKEN }}@github.com/patel-hiral/production.git
          git fetch prod_repo

      - name: Push Changes to Production Repo
        run: |
          git push prod_repo main:main --force
