name: Push Stable Code to Production Repo

on:
  push:
    branches:
      - main  # Runs only when main is updated

jobs:
  push-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev Repository
        uses: actions/checkout@v3

      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_DEPLOY_KEY }}" > ~/.ssh/prod-deploy-key
          chmod 600 ~/.ssh/prod-deploy-key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/prod-deploy-key

      - name: Clone Production Repository
        run: |
          git clone --bare git@github.com:patel-hiral/production.git prod-repo
          cd prod-repo
          git push --mirror git@github.com:patel-hiral/production.git

      - name: Push Code to Production Repository
        run: |
          cd prod-repo
          git fetch --all
          git reset --hard origin/main
          git pull origin main
          git push origin main
