name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to allow merging

      - name: Set Git Identity
        run: |
          git config --global user.email "patel.hiral@differenzsystem.com"
          git config --global user.name "Hiral Patel"

      - name: Add Production Remote
        run: |
          git remote add prod git@github.com:patel-hiral/production.git
          git fetch prod main  # Fetch latest changes from production

      - name: Merge Without Workflow Files
        run: |
          git checkout main
          git pull origin main  # Ensure latest Dev changes
          git checkout -b temp-branch
          git pull prod main --rebase  # Rebase production changes
          git checkout prod/main -- .  # Bring in all production files
          git reset HEAD .github/workflows/*  # Exclude workflow files
          git commit -m "Merge Dev to Production without workflow files"
          git push --force prod temp-branch:main  # Push with force to avoid conflicts
