name: Push to Production Repository
 
# Triggers Action When We Push in Main Branch On Development Repository
on:
  push:
    branches:
      - main
 
jobs:
  push_to_production:
    runs-on: ubuntu-latest
 
    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
 
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to allow merging
 
      - name: Set Git Identity
        run: |
            git config --global user.email "patel.hiral@differenzsystem.com"
            git config --global user.name "Hiral Patel"
 
      - name: Add Production Repository as Remote origin
        run: git remote add prod git@github.com:patel-hiral/production.git
 
      - name: Fetch Latest Changes from production repository
        run: git fetch prod main  # Get latest changes from production
 
      # Handles Merge Conflicts
      - name: Merge Dev Repo into Production
        run: |
          git checkout main
          git merge prod main --strategy=ours || true  # Keeps our changes, prevents failure
          rm -rf .github/workflows  # Force delete the entire workflows folder
          git commit -m "Auto-resolved merge conflicts from Dev to Production" || true
          git push prod main --force  # Force push changes to Production