name: Deploy to Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout Dev Repository
      - name: Checkout Dev Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to avoid merge conflicts

      # Set up Git user for commits
      - name: Configure Git
        run: |
          git config --global user.name "Hiral Patel"
          git config --global user.email "hiral.patel@differenzsystem.com"

      # Add Production Remote
      - name: Add Production Remote
        run: |
          git remote add prod git@github.com:patel-hiral/production.git
          git fetch prod main

      # Handle Merge Conflicts Automatically
      - name: Merge Dev into Production
        run: |
          git checkout main
          git merge prod/main --strategy=ours || true  # Keeps our changes, prevents failure
          git commit -am "Auto-resolved merge conflicts from Dev to Production" || true
          git push prod main --force  # Force push changes to Production
