name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      
      - name: Checkout Repository
        uses: actions/checkout@v4  # Ensures Git repo is available

      - name: Verify Git Repository
        run: git status  # Checks if the directory is a valid Git repo

      - name: Add Production Remote
        run: git remote add prod git@github.com:patel-hiral/production.git

      - name: Push to Production
        run: git push prod main
